// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// max_colCpp
IntegerVector max_colCpp(const int N, int iMax, IntegerVector cn, IntegerVector clast);
RcppExport SEXP clust_max_colCpp(SEXP NSEXP, SEXP iMaxSEXP, SEXP cnSEXP, SEXP clastSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type iMax(iMaxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cn(cnSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type clast(clastSEXP);
    __result = Rcpp::wrap(max_colCpp(N, iMax, cn, clast));
    return __result;
END_RCPP
}
// prod_YxCpp
NumericVector prod_YxCpp(NumericVector vY, IntegerVector clast, IntegerVector ccenter);
RcppExport SEXP clust_prod_YxCpp(SEXP vYSEXP, SEXP clastSEXP, SEXP ccenterSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type vY(vYSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type clast(clastSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ccenter(ccenterSEXP);
    __result = Rcpp::wrap(prod_YxCpp(vY, clast, ccenter));
    return __result;
END_RCPP
}
// st_matCpp
NumericVector st_matCpp(NumericMatrix X, IntegerVector last, IntegerVector center, int T);
RcppExport SEXP clust_st_matCpp(SEXP XSEXP, SEXP lastSEXP, SEXP centerSEXP, SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type last(lastSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type center(centerSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    __result = Rcpp::wrap(st_matCpp(X, last, center, T));
    return __result;
END_RCPP
}
