# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

max_colCpp <- function(N, iMax, cn, clast) {
    .Call('clust_max_colCpp', PACKAGE = 'clust', N, iMax, cn, clast)
}

prod_YxCpp <- function(vY, clast, ccenter) {
    .Call('clust_prod_YxCpp', PACKAGE = 'clust', vY, clast, ccenter)
}

st_matCpp <- function(X, last, center, T) {
    .Call('clust_st_matCpp', PACKAGE = 'clust', X, last, center, T)
}

