---
title: "Running clust with Simulated Data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Intro to clust}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


#Introduction

Load *clust*

```{r, message=FALSE, warning=FALSE}
library("clust")
```




##Prepare Data

This example is adapted from **Applied Spatial Statistics for Public Health Data** by Lance Waller and Carol Gotway (2004).

We will create 4 time periods.
Notice that these are not standardized in the beginning. Clust will do this internally.

```{r}
#set initial
set.seed(8212017)
ncentroids <- 25

#generate expected, observed, period, id, and utm coordinates

##generate data
observed_disease <- rnbinom(ncentroids*4, 5 ,prob = 0.3)
expect_disease <- rnbinom(ncentroids*4, 5 ,prob = 0.32)
id <- as.character(rep(1:25, each=4))
period <- as.factor(rep(1:25, times = 4))

##put together the vectors into a dataframe
df <-cbind.data.frame(id, period, observed_disease, expect_disease)
str(df)
```




##Explore the Data


##Using *clust*


```{r}

##get coordinates
easting <- c(380775.664, 429643.221, 467554.861,398199.760,375444.918, 400212.232, 415835.404,454305.848, 446806.707,434104.476, 344402.500, 374321.622,493865.557, 412989.631, 325675.232,364082.121, 463548.477,383019.454, 366888.053, 454245.142, 321340.050, 408546.111, 334630.866, 440181.095,388725.451)

northing <- c(3606798.382, 3587905.874, 3581547.440, 3581861.311, 3558825.264, 3549337.656, 3560344.423, 3544080.578, 3524848.421, 3505692.396, 3524049.993, 3513589.072, 3539584.049, 3497227.698, 3487194.532, 3494227.776, 3486352.845, 3473351.819, 3438399.181, 3456655.732, 3464443.158, 3453357.994, 3423796.886, 3425482.335, 3424758.917)
```


Set up initial parameters:

```{r}
#Set Some Initial Conditions
x=easting/1000 #dividing by 1000 because utm coordinates and radius will be based on km
y=northing/1000
rMax=20 #maximum radius for definition of potential cluster
Time=4
#nsim=100
nsim=1
center=2
radius= 18
timeperiod=c(1:4)
risk.ratio=1
theta = NULL
threshold <- c(0.9, 0.5)
mods <- c("QuasiPoisson", "Poisson")

```


```{r}

res <- clust_sim(x,y,rMax,df$period, df$expect_disease, df$observed_disease, Time,
                    nsim,center, radius, risk.ratio, timeperiod, utm=TRUE, byrow=TRUE, 
                    threshold, space= "both", theta = theta,nullmod=TRUE)

#save results
(sim.i <- paste0("sim","_","center","_",center,"radius",radius,"_", "start",
                 "_",as.numeric(paste(timeperiod, collapse = "")),"_","rr","_",gsub("[.]","",risk.ratio)))
(filename <- paste0("vignettes/sampleoutput/",sim.i,"TEST.RData"))
save(res, file = filename)

#Print Detection for the Simulation
(tabn <- rbind("******",cbind(radius,risk.ratio,center,time=as.numeric(paste(timeperiod, collapse = "")), mod = "ST",
                              rbind("QuasiPois",res$detect.out.qp.st), rbind("Pois",res$detect.out.p.st)), 
               cbind(radius,risk.ratio,center,time=as.numeric(paste(timeperiod, collapse = "")), mod = "Space",
                     rbind("QuasiPois",res$detect.out.qp.s), rbind("Pois",res$detect.out.p.s))))
```




```{r}
#make maps
pdfname <- paste0("figures/simulations/sim","_","center","_",center,"radius",radius,"_", "start",
                  "_",as.numeric(paste(timeperiod, collapse = "")),"_","rr","_",gsub("[.]","",risk.ratio),"TESTEST.pdf")
easyplot(pdfname, res, mods, space="both")

```


