// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// max_colCpp
IntegerVector max_colCpp(const int N, int iMax, IntegerVector cn, IntegerVector clast);
RcppExport SEXP _clust_max_colCpp(SEXP NSEXP, SEXP iMaxSEXP, SEXP cnSEXP, SEXP clastSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type iMax(iMaxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cn(cnSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type clast(clastSEXP);
    rcpp_result_gen = Rcpp::wrap(max_colCpp(N, iMax, cn, clast));
    return rcpp_result_gen;
END_RCPP
}
// prod_YxCpp
NumericVector prod_YxCpp(NumericVector vY, IntegerVector clast, IntegerVector ccenter);
RcppExport SEXP _clust_prod_YxCpp(SEXP vYSEXP, SEXP clastSEXP, SEXP ccenterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vY(vYSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type clast(clastSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ccenter(ccenterSEXP);
    rcpp_result_gen = Rcpp::wrap(prod_YxCpp(vY, clast, ccenter));
    return rcpp_result_gen;
END_RCPP
}
// st_matCpp
NumericVector st_matCpp(NumericMatrix X, IntegerVector last, IntegerVector center, int T);
RcppExport SEXP _clust_st_matCpp(SEXP XSEXP, SEXP lastSEXP, SEXP centerSEXP, SEXP TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type last(lastSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type center(centerSEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    rcpp_result_gen = Rcpp::wrap(st_matCpp(X, last, center, T));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_clust_max_colCpp", (DL_FUNC) &_clust_max_colCpp, 4},
    {"_clust_prod_YxCpp", (DL_FUNC) &_clust_prod_YxCpp, 3},
    {"_clust_st_matCpp", (DL_FUNC) &_clust_st_matCpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_clust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
