# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates maximum column for spatial radius
#' @title return maximum center based on a raidus supplied
#' @param N total number of centroids
#' @param iMax each row of clusters dataframe (from clusters2df function)
#' @param cn identifier of centroid to which the count belongs to
#' @param clast last observation of that centroid group
#' @return integer vector for the last observation in a sequence of observations by growing radius, given users rMax specifications.
#' @export
max_colCpp <- function(N, iMax, cn, clast) {
    .Call('_clusso_max_colCpp', PACKAGE = 'clusso', N, iMax, cn, clast)
}

#' @title
#' Calculates sequencce of values based on maximum radius
#' @name prod_YxCpp
#' @param vY numeric vector
#' @param clast last observation in sequence 
#' @param ccenter centroid value
#' @return numeric vector that feeds into st_matCpp function
#' @description helper function
#' @export
prod_YxCpp <- function(vY, clast, ccenter) {
    .Call('_clusso_prod_YxCpp', PACKAGE = 'clusso', vY, clast, ccenter)
}

#' @title
#' Helper function
#' @name st_matCpp
#' @param X takes in numeric matrix
#' @param last takes in integer vector of last observation in a sequence given a radius
#' @param center centroid value
#' @param T integer
#' @return numeric vector
#' @description helper function
#' @export
st_matCpp <- function(X, last, center, T) {
    .Call('_clusso_st_matCpp', PACKAGE = 'clusso', X, last, center, T)
}

